/**
 * RiddleCity Seed Data
 * Initial catalog data for buildings, furnishings, defense systems, and policies
 */

// BUILDING CATALOG SEED DATA
export const BUILDING_CATALOG_SEED = [
  // RESIDENTIAL
  {
    buildingType: 'cottage',
    category: 'residential',
    name: 'Cottage',
    description: 'A simple dwelling for your citizens',
    icon: '🏠',
    image: '/riddlecity/buildings/cottage.png',
    creditCost: '500.00',
    materialCost: '100.00',
    energyCost: '0.00',
    constructionTime: 60,
    requiredCityLevel: 1,
    requiredPopulation: 0,
    plotSpaceRequired: 1,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '5.00',
    consumesFood: '0.00',
    upkeepCost: '10.00',
    housingCapacity: 2,
    shopSlots: 0,
    defenseBonus: 0,
    happinessBonus: 5,
    canUpgrade: true,
    upgradesTo: 'townhouse',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'townhouse',
    category: 'residential',
    name: 'Townhouse',
    description: 'A larger home for growing families',
    icon: '🏘️',
    image: '/riddlecity/buildings/townhouse.png',
    creditCost: '1500.00',
    materialCost: '300.00',
    energyCost: '0.00',
    constructionTime: 120,
    requiredCityLevel: 2,
    requiredPopulation: 10,
    plotSpaceRequired: 2,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '10.00',
    consumesFood: '0.00',
    upkeepCost: '25.00',
    housingCapacity: 5,
    shopSlots: 0,
    defenseBonus: 0,
    happinessBonus: 10,
    canUpgrade: true,
    upgradesTo: 'manor',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'manor',
    category: 'residential',
    name: 'Manor',
    description: 'An elegant manor for wealthy citizens',
    icon: '🏛️',
    image: '/riddlecity/buildings/manor.png',
    creditCost: '5000.00',
    materialCost: '1000.00',
    energyCost: '0.00',
    constructionTime: 300,
    requiredCityLevel: 4,
    requiredPopulation: 50,
    plotSpaceRequired: 4,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '20.00',
    consumesFood: '0.00',
    upkeepCost: '75.00',
    housingCapacity: 15,
    shopSlots: 0,
    defenseBonus: 0,
    happinessBonus: 25,
    canUpgrade: false,
    upgradesTo: null,
    isActive: true,
    isSpecial: false
  },

  // COMMERCIAL
  {
    buildingType: 'market_stall',
    category: 'commercial',
    name: 'Market Stall',
    description: 'A simple stall for selling goods',
    icon: '🛒',
    image: '/riddlecity/buildings/market_stall.png',
    creditCost: '1000.00',
    materialCost: '200.00',
    energyCost: '0.00',
    constructionTime: 90,
    requiredCityLevel: 1,
    requiredPopulation: 5,
    plotSpaceRequired: 1,
    producesCredits: '50.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '5.00',
    consumesFood: '0.00',
    upkeepCost: '15.00',
    housingCapacity: 0,
    shopSlots: 1,
    defenseBonus: 0,
    happinessBonus: 5,
    canUpgrade: true,
    upgradesTo: 'shop',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'shop',
    category: 'commercial',
    name: 'Shop',
    description: 'A proper shop for commerce',
    icon: '🏪',
    image: '/riddlecity/buildings/shop.png',
    creditCost: '3000.00',
    materialCost: '600.00',
    energyCost: '0.00',
    constructionTime: 180,
    requiredCityLevel: 2,
    requiredPopulation: 15,
    plotSpaceRequired: 2,
    producesCredits: '150.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '15.00',
    consumesFood: '0.00',
    upkeepCost: '40.00',
    housingCapacity: 0,
    shopSlots: 3,
    defenseBonus: 0,
    happinessBonus: 10,
    canUpgrade: true,
    upgradesTo: 'marketplace',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'marketplace',
    category: 'commercial',
    name: 'Marketplace',
    description: 'A bustling marketplace hub',
    icon: '🏬',
    image: '/riddlecity/buildings/marketplace.png',
    creditCost: '10000.00',
    materialCost: '2000.00',
    energyCost: '0.00',
    constructionTime: 360,
    requiredCityLevel: 4,
    requiredPopulation: 50,
    plotSpaceRequired: 6,
    producesCredits: '500.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '40.00',
    consumesFood: '0.00',
    upkeepCost: '120.00',
    housingCapacity: 0,
    shopSlots: 10,
    defenseBonus: 0,
    happinessBonus: 30,
    canUpgrade: false,
    upgradesTo: null,
    isActive: true,
    isSpecial: true
  },

  // INDUSTRIAL
  {
    buildingType: 'quarry',
    category: 'industrial',
    name: 'Quarry',
    description: 'Extracts stone and materials',
    icon: '⛏️',
    image: '/riddlecity/buildings/quarry.png',
    creditCost: '2000.00',
    materialCost: '400.00',
    energyCost: '0.00',
    constructionTime: 150,
    requiredCityLevel: 2,
    requiredPopulation: 10,
    plotSpaceRequired: 3,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '100.00',
    consumesEnergy: '30.00',
    consumesFood: '10.00',
    upkeepCost: '50.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 0,
    happinessBonus: -5,
    canUpgrade: true,
    upgradesTo: 'industrial_quarry',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'farm',
    category: 'industrial',
    name: 'Farm',
    description: 'Produces food for your city',
    icon: '🌾',
    image: '/riddlecity/buildings/farm.png',
    creditCost: '1500.00',
    materialCost: '300.00',
    energyCost: '0.00',
    constructionTime: 120,
    requiredCityLevel: 1,
    requiredPopulation: 5,
    plotSpaceRequired: 4,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '200.00',
    producesMaterials: '0.00',
    consumesEnergy: '10.00',
    consumesFood: '0.00',
    upkeepCost: '20.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 0,
    happinessBonus: 5,
    canUpgrade: true,
    upgradesTo: 'plantation',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'power_plant',
    category: 'industrial',
    name: 'Power Plant',
    description: 'Generates energy for your city',
    icon: '⚡',
    image: '/riddlecity/buildings/power_plant.png',
    creditCost: '5000.00',
    materialCost: '1500.00',
    energyCost: '0.00',
    constructionTime: 240,
    requiredCityLevel: 3,
    requiredPopulation: 30,
    plotSpaceRequired: 5,
    producesCredits: '0.00',
    producesEnergy: '500.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '0.00',
    consumesFood: '0.00',
    upkeepCost: '100.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 0,
    happinessBonus: -10,
    canUpgrade: true,
    upgradesTo: 'advanced_power_plant',
    isActive: true,
    isSpecial: false
  },

  // DEFENSE
  {
    buildingType: 'wooden_wall',
    category: 'defense',
    name: 'Wooden Wall',
    description: 'Basic defensive wall',
    icon: '🛡️',
    image: '/riddlecity/buildings/wooden_wall.png',
    creditCost: '800.00',
    materialCost: '200.00',
    energyCost: '0.00',
    constructionTime: 90,
    requiredCityLevel: 1,
    requiredPopulation: 10,
    plotSpaceRequired: 1,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '0.00',
    consumesFood: '0.00',
    upkeepCost: '10.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 10,
    happinessBonus: 5,
    canUpgrade: true,
    upgradesTo: 'stone_wall',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'watchtower',
    category: 'defense',
    name: 'Watchtower',
    description: 'Provides early warning of threats',
    icon: '🗼',
    image: '/riddlecity/buildings/watchtower.png',
    creditCost: '1200.00',
    materialCost: '300.00',
    energyCost: '0.00',
    constructionTime: 120,
    requiredCityLevel: 2,
    requiredPopulation: 15,
    plotSpaceRequired: 2,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '5.00',
    consumesFood: '0.00',
    upkeepCost: '15.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 15,
    happinessBonus: 10,
    canUpgrade: true,
    upgradesTo: 'guard_tower',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'barracks',
    category: 'defense',
    name: 'Barracks',
    description: 'Train and house guards',
    icon: '⚔️',
    image: '/riddlecity/buildings/barracks.png',
    creditCost: '3000.00',
    materialCost: '800.00',
    energyCost: '0.00',
    constructionTime: 180,
    requiredCityLevel: 3,
    requiredPopulation: 25,
    plotSpaceRequired: 4,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '20.00',
    consumesFood: '30.00',
    upkeepCost: '60.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 50,
    happinessBonus: 15,
    canUpgrade: false,
    upgradesTo: null,
    isActive: true,
    isSpecial: false
  },

  // CIVIC
  {
    buildingType: 'town_hall',
    category: 'civic',
    name: 'Town Hall',
    description: 'The heart of your city government',
    icon: '🏛️',
    image: '/riddlecity/buildings/town_hall.png',
    creditCost: '10000.00',
    materialCost: '3000.00',
    energyCost: '0.00',
    constructionTime: 600,
    requiredCityLevel: 1,
    requiredPopulation: 0,
    plotSpaceRequired: 8,
    producesCredits: '100.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '30.00',
    consumesFood: '0.00',
    upkeepCost: '50.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 25,
    happinessBonus: 50,
    canUpgrade: false,
    upgradesTo: null,
    isActive: true,
    isSpecial: true
  },
  {
    buildingType: 'park',
    category: 'civic',
    name: 'Park',
    description: 'A green space for citizens to relax',
    icon: '🌳',
    image: '/riddlecity/buildings/park.png',
    creditCost: '2000.00',
    materialCost: '400.00',
    energyCost: '0.00',
    constructionTime: 150,
    requiredCityLevel: 2,
    requiredPopulation: 20,
    plotSpaceRequired: 3,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '5.00',
    consumesFood: '0.00',
    upkeepCost: '15.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 0,
    happinessBonus: 30,
    canUpgrade: true,
    upgradesTo: 'grand_park',
    isActive: true,
    isSpecial: false
  },
  {
    buildingType: 'library',
    category: 'civic',
    name: 'Library',
    description: 'Increases education and culture',
    icon: '📚',
    image: '/riddlecity/buildings/library.png',
    creditCost: '4000.00',
    materialCost: '1000.00',
    energyCost: '0.00',
    constructionTime: 240,
    requiredCityLevel: 3,
    requiredPopulation: 30,
    plotSpaceRequired: 4,
    producesCredits: '0.00',
    producesEnergy: '0.00',
    producesFood: '0.00',
    producesMaterials: '0.00',
    consumesEnergy: '15.00',
    consumesFood: '0.00',
    upkeepCost: '30.00',
    housingCapacity: 0,
    shopSlots: 0,
    defenseBonus: 0,
    happinessBonus: 25,
    canUpgrade: false,
    upgradesTo: null,
    isActive: true,
    isSpecial: false
  }
];

// FURNISHING CATALOG SEED DATA
export const FURNISHING_CATALOG_SEED = [
  // FURNITURE
  {
    furnishingType: 'wooden_table',
    category: 'furniture',
    name: 'Wooden Table',
    description: 'A simple wooden table',
    icon: '🪑',
    model: '/models/wooden_table.glb',
    creditCost: '50.00',
    canPlaceIn: ['cottage', 'townhouse', 'manor', 'shop', 'marketplace'],
    sizeX: 2,
    sizeY: 1,
    happinessBonus: 2,
    productionBonus: '0.00',
    isActive: true
  },
  {
    furnishingType: 'chair',
    category: 'furniture',
    name: 'Chair',
    description: 'A comfortable chair',
    icon: '🪑',
    model: '/models/chair.glb',
    creditCost: '25.00',
    canPlaceIn: ['cottage', 'townhouse', 'manor', 'shop', 'marketplace', 'town_hall', 'library'],
    sizeX: 1,
    sizeY: 1,
    happinessBonus: 1,
    productionBonus: '0.00',
    isActive: true
  },
  {
    furnishingType: 'bed',
    category: 'furniture',
    name: 'Bed',
    description: 'A cozy bed for sleeping',
    icon: '🛏️',
    model: '/models/bed.glb',
    creditCost: '100.00',
    canPlaceIn: ['cottage', 'townhouse', 'manor'],
    sizeX: 2,
    sizeY: 2,
    happinessBonus: 5,
    productionBonus: '0.00',
    isActive: true
  },
  {
    furnishingType: 'bookshelf',
    category: 'furniture',
    name: 'Bookshelf',
    description: 'Stores books and knowledge',
    icon: '📚',
    model: '/models/bookshelf.glb',
    creditCost: '150.00',
    canPlaceIn: ['cottage', 'townhouse', 'manor', 'library', 'town_hall'],
    sizeX: 2,
    sizeY: 1,
    happinessBonus: 3,
    productionBonus: '0.05',
    isActive: true
  },

  // DECORATIONS
  {
    furnishingType: 'painting',
    category: 'decoration',
    name: 'Painting',
    description: 'A beautiful artwork',
    icon: '🖼️',
    model: '/models/painting.glb',
    creditCost: '200.00',
    canPlaceIn: ['cottage', 'townhouse', 'manor', 'shop', 'marketplace', 'town_hall', 'library'],
    sizeX: 1,
    sizeY: 1,
    happinessBonus: 10,
    productionBonus: '0.00',
    isActive: true
  },
  {
    furnishingType: 'plant',
    category: 'decoration',
    name: 'Potted Plant',
    description: 'Brings nature indoors',
    icon: '🪴',
    model: '/models/plant.glb',
    creditCost: '75.00',
    canPlaceIn: ['cottage', 'townhouse', 'manor', 'shop', 'marketplace', 'town_hall', 'library'],
    sizeX: 1,
    sizeY: 1,
    happinessBonus: 5,
    productionBonus: '0.00',
    isActive: true
  },
  {
    furnishingType: 'chandelier',
    category: 'decoration',
    name: 'Chandelier',
    description: 'Elegant lighting fixture',
    icon: '💡',
    model: '/models/chandelier.glb',
    creditCost: '500.00',
    canPlaceIn: ['townhouse', 'manor', 'marketplace', 'town_hall', 'library'],
    sizeX: 2,
    sizeY: 2,
    happinessBonus: 15,
    productionBonus: '0.00',
    isActive: true
  },

  // EQUIPMENT
  {
    furnishingType: 'shop_counter',
    category: 'equipment',
    name: 'Shop Counter',
    description: 'Essential for any shop',
    icon: '🏪',
    model: '/models/counter.glb',
    creditCost: '300.00',
    canPlaceIn: ['market_stall', 'shop', 'marketplace'],
    sizeX: 3,
    sizeY: 1,
    happinessBonus: 0,
    productionBonus: '0.10',
    isActive: true
  },
  {
    furnishingType: 'workbench',
    category: 'equipment',
    name: 'Workbench',
    description: 'Increases production efficiency',
    icon: '🔨',
    model: '/models/workbench.glb',
    creditCost: '250.00',
    canPlaceIn: ['quarry', 'farm', 'power_plant'],
    sizeX: 2,
    sizeY: 2,
    happinessBonus: 0,
    productionBonus: '0.15',
    isActive: true
  },
  {
    furnishingType: 'storage_chest',
    category: 'equipment',
    name: 'Storage Chest',
    description: 'Stores resources',
    icon: '📦',
    model: '/models/chest.glb',
    creditCost: '100.00',
    canPlaceIn: ['cottage', 'townhouse', 'manor', 'shop', 'marketplace', 'quarry', 'farm'],
    sizeX: 1,
    sizeY: 1,
    happinessBonus: 1,
    productionBonus: '0.00',
    isActive: true
  }
];

// POLICY DEFINITIONS SEED DATA
export const POLICY_DEFINITIONS_SEED = [
  // ECONOMY
  {
    policyType: 'low_taxes',
    category: 'economy',
    name: 'Low Taxes',
    description: 'Reduce taxes to increase happiness but decrease revenue',
    happinessModifier: 15,
    productionModifier: '0.00',
    upkeepModifier: '0.10',
    populationGrowthModifier: '0.20',
    implementationCost: '1000.00',
    dailyCost: '0.00',
    requiredCityLevel: 1,
    isActive: true
  },
  {
    policyType: 'high_taxes',
    category: 'economy',
    name: 'High Taxes',
    description: 'Increase taxes for more revenue but lower happiness',
    happinessModifier: -15,
    productionModifier: '0.00',
    upkeepModifier: '-0.20',
    populationGrowthModifier: '-0.10',
    implementationCost: '500.00',
    dailyCost: '0.00',
    requiredCityLevel: 1,
    isActive: true
  },
  {
    policyType: 'trade_incentives',
    category: 'economy',
    name: 'Trade Incentives',
    description: 'Boost commercial production',
    happinessModifier: 5,
    productionModifier: '0.25',
    upkeepModifier: '0.00',
    populationGrowthModifier: '0.10',
    implementationCost: '2000.00',
    dailyCost: '100.00',
    requiredCityLevel: 2,
    isActive: true
  },

  // SOCIAL
  {
    policyType: 'public_works',
    category: 'social',
    name: 'Public Works Program',
    description: 'Invest in infrastructure and happiness',
    happinessModifier: 25,
    productionModifier: '0.10',
    upkeepModifier: '0.15',
    populationGrowthModifier: '0.15',
    implementationCost: '5000.00',
    dailyCost: '200.00',
    requiredCityLevel: 3,
    isActive: true
  },
  {
    policyType: 'education_program',
    category: 'social',
    name: 'Education Program',
    description: 'Improve citizen skills and productivity',
    happinessModifier: 10,
    productionModifier: '0.20',
    upkeepModifier: '0.05',
    populationGrowthModifier: '0.05',
    implementationCost: '3000.00',
    dailyCost: '150.00',
    requiredCityLevel: 2,
    isActive: true
  },

  // MILITARY
  {
    policyType: 'military_focus',
    category: 'military',
    name: 'Military Focus',
    description: 'Strengthen defenses at economic cost',
    happinessModifier: -5,
    productionModifier: '-0.10',
    upkeepModifier: '0.20',
    populationGrowthModifier: '0.00',
    implementationCost: '4000.00',
    dailyCost: '250.00',
    requiredCityLevel: 3,
    isActive: true
  },
  {
    policyType: 'peacetime_economy',
    category: 'military',
    name: 'Peacetime Economy',
    description: 'Focus on production over defense',
    happinessModifier: 10,
    productionModifier: '0.15',
    upkeepModifier: '-0.05',
    populationGrowthModifier: '0.10',
    implementationCost: '2000.00',
    dailyCost: '0.00',
    requiredCityLevel: 2,
    isActive: true
  },

  // ENVIRONMENT
  {
    policyType: 'green_initiative',
    category: 'environment',
    name: 'Green Initiative',
    description: 'Eco-friendly policies boost happiness',
    happinessModifier: 20,
    productionModifier: '-0.05',
    upkeepModifier: '0.10',
    populationGrowthModifier: '0.15',
    implementationCost: '6000.00',
    dailyCost: '300.00',
    requiredCityLevel: 4,
    isActive: true
  },
  {
    policyType: 'industrial_boom',
    category: 'environment',
    name: 'Industrial Boom',
    description: 'Maximize production at environmental cost',
    happinessModifier: -10,
    productionModifier: '0.35',
    upkeepModifier: '-0.10',
    populationGrowthModifier: '0.05',
    implementationCost: '3000.00',
    dailyCost: '100.00',
    requiredCityLevel: 3,
    isActive: true
  }
];

// DEFENSE SYSTEMS CATALOG SEED DATA
export const DEFENSE_SYSTEMS_CATALOG_SEED = [
  {
    systemType: 'stone_wall',
    name: 'Stone Wall',
    description: 'Sturdy stone fortifications',
    creditCost: '2000.00',
    materialCost: '500.00',
    defenseStrength: 25,
    upkeepCost: '20.00',
    requiredCityLevel: 2,
    isActive: true
  },
  {
    systemType: 'guard_tower',
    name: 'Guard Tower',
    description: 'Advanced watchtower with better range',
    creditCost: '3000.00',
    materialCost: '800.00',
    defenseStrength: 35,
    upkeepCost: '30.00',
    requiredCityLevel: 3,
    isActive: true
  },
  {
    systemType: 'fortress_wall',
    name: 'Fortress Wall',
    description: 'Impenetrable fortress walls',
    creditCost: '8000.00',
    materialCost: '2000.00',
    defenseStrength: 75,
    upkeepCost: '60.00',
    requiredCityLevel: 4,
    isActive: true
  },
  {
    systemType: 'catapult',
    name: 'Catapult',
    description: 'Offensive defense system',
    creditCost: '5000.00',
    materialCost: '1200.00',
    defenseStrength: 50,
    upkeepCost: '40.00',
    requiredCityLevel: 3,
    isActive: true
  }
];
